'use client';

import { AArrowDown, AArrowUp, ALargeSmall, Accessibility, Activity, Airplay, AirVent, AlarmClockCheck, AlarmClockMinus, AlarmClockPlus, AlarmClockOff, AlarmClock, AlarmSmoke, Album, AlignCenterHorizontal, AlignCenterVertical, AlignEndHorizontal, AlignEndVertical, AlignHorizontalDistributeCenter, AlignHorizontalDistributeEnd, AlignHorizontalDistributeStart, AlignHorizontalJustifyCenter, AlignHorizontalJustifyEnd, AlignHorizontalJustifyStart, AlignHorizontalSpaceAround, AlignHorizontalSpaceBetween, AlignStartHorizontal, AlignStartVertical, AlignVerticalDistributeCenter, AlignVerticalDistributeEnd, AlignVerticalDistributeStart, AlignVerticalJustifyCenter, AlignVerticalJustifyStart, AlignVerticalJustifyEnd, AlignVerticalSpaceAround, AlignVerticalSpaceBetween, Ambulance, Ampersand, Ampersands, Anchor, Angry, Amphora, Annoyed, Antenna, Anvil, Aperture, AppWindowMac, Apple, AppWindow, ArchiveRestore, ArchiveX, Archive, Armchair, ArrowBigDownDash, ArrowBigDown, ArrowBigLeftDash, ArrowBigLeft, ArrowBigRightDash, ArrowBigRight, ArrowBigUpDash, ArrowBigUp, ArrowDown01, ArrowDown10, ArrowDownAZ, ArrowDownFromLine, ArrowDownLeft, ArrowDownNarrowWide, ArrowDownRight, ArrowDownToDot, ArrowDownToLine, ArrowDownUp, ArrowDownWideNarrow, ArrowDownZA, ArrowDown, ArrowLeftFromLine, ArrowLeftToLine, ArrowLeftRight, ArrowRightFromLine, ArrowLeft, ArrowRightLeft, ArrowRightToLine, ArrowUp01, ArrowRight, ArrowUp10, ArrowUpAZ, ArrowUpDown, ArrowUpFromDot, ArrowUpFromLine, ArrowUpLeft, ArrowUpRight, ArrowUpNarrowWide, ArrowUpToLine, ArrowUpWideNarrow, ArrowUpZA, ArrowUp, ArrowsUpFromLine, Asterisk, AtSign, Atom, AudioWaveform } from 'lucide-react';

const icons = [AArrowDown, AArrowUp, ALargeSmall, Accessibility, Activity, Airplay, AirVent, AlarmClockCheck, AlarmClockMinus, AlarmClockPlus, AlarmClockOff, AlarmClock, AlarmSmoke, Album, AlignCenterHorizontal, AlignCenterVertical, AlignEndHorizontal, AlignEndVertical, AlignHorizontalDistributeCenter, AlignHorizontalDistributeEnd, AlignHorizontalDistributeStart, AlignHorizontalJustifyCenter, AlignHorizontalJustifyEnd, AlignHorizontalJustifyStart, AlignHorizontalSpaceAround, AlignHorizontalSpaceBetween, AlignStartHorizontal, AlignStartVertical, AlignVerticalDistributeCenter, AlignVerticalDistributeEnd, AlignVerticalDistributeStart, AlignVerticalJustifyCenter, AlignVerticalJustifyStart, AlignVerticalJustifyEnd, AlignVerticalSpaceAround, AlignVerticalSpaceBetween, Ambulance, Ampersand, Ampersands, Anchor, Angry, Amphora, Annoyed, Antenna, Anvil, Aperture, AppWindowMac, Apple, AppWindow, ArchiveRestore, ArchiveX, Archive, Armchair, ArrowBigDownDash, ArrowBigDown, ArrowBigLeftDash, ArrowBigLeft, ArrowBigRightDash, ArrowBigRight, ArrowBigUpDash, ArrowBigUp, ArrowDown01, ArrowDown10, ArrowDownAZ, ArrowDownFromLine, ArrowDownLeft, ArrowDownNarrowWide, ArrowDownRight, ArrowDownToDot, ArrowDownToLine, ArrowDownUp, ArrowDownWideNarrow, ArrowDownZA, ArrowDown, ArrowLeftFromLine, ArrowLeftToLine, ArrowLeftRight, ArrowRightFromLine, ArrowLeft, ArrowRightLeft, ArrowRightToLine, ArrowUp01, ArrowRight, ArrowUp10, ArrowUpAZ, ArrowUpDown, ArrowUpFromDot, ArrowUpFromLine, ArrowUpLeft, ArrowUpRight, ArrowUpNarrowWide, ArrowUpToLine, ArrowUpWideNarrow, ArrowUpZA, ArrowUp, ArrowsUpFromLine, Asterisk, AtSign, Atom, AudioWaveform];

export function LucideScenario100() {
  return (
    <div className="icon-grid">
      {icons.map((Icon, idx) => (
        <div key={idx} className="icon-cell"><Icon size={20} /></div>
      ))}
    </div>
  );
}
